const CATALOG = {
  CSS系列: [
    'css/box',
    'css/selector',
    'css/em_px_rem_vh_vw',
    'css/dp_px_dpr_ppi',
    'css/hide_attributes',
    'css/BFC',
    'css/center',
    'css/column_layout',
    'css/flexbox',
    'css/grid',
    'css/css3_features',
    'css/animation',
    'css/layout_painting',
    'css/responsive_layout',
    'css/css_performance',
    'css/single_multi_line',
    'css/visual_scrolling',
    'css/triangle',
    'css/less_12px',
    'css/sass_less_stylus'
  ],
  JavaScript系列: [
    "JavaScript/data_type",
    "JavaScript/array_api",
    "JavaScript/string_api",
    "JavaScript/type_conversion",
    "JavaScript/== _===",
    "JavaScript/copy",
    "JavaScript/closure",
    "JavaScript/scope",
    "JavaScript/prototype",
    "JavaScript/inherit",
    "JavaScript/this",
    "JavaScript/context_stack",
    "JavaScript/event_Model",
    "JavaScript/typeof_instanceof",
    "JavaScript/event_agent",
    "JavaScript/new",
    "JavaScript/ajax",
    "JavaScript/bind_call_apply",
    "JavaScript/regexp",
    "JavaScript/event_loop",
    "JavaScript/Dom",
    "JavaScript/BOM",
    "JavaScript/tail_recursion",
    "JavaScript/memory_leak",
    "JavaScript/cache",
    "JavaScript/functional_programming",
    "JavaScript/function_cache",
    "JavaScript/loss_accuracy",
    "JavaScript/debounce_throttle",
    "JavaScript/visible",
    "JavaScript/continue_to_upload",
    "JavaScript/pull_up_loading_pull_down_refresh",
    "JavaScript/single_sign",
    "JavaScript/security"
  ],
  ES6系列: [
    "es6/var_let_const",
    "es6/array",
    "es6/object",
    "es6/function",
    "es6/set_map",
    "es6/promise",
    "es6/generator",
    "es6/proxy",
    "es6/module",
    "es6/decorator"
  ],
  Vue系列: [
    "vue/spa",
    "vue/show_if",
    "vue/new_vue",
    "vue/lifecycle",
    "vue/if_for",
    "vue/first_page_time",
    "vue/data",
    "vue/data_object_add_attrs",
    "vue/components_plugin",
    "vue/communication",
    "vue/bind",
    "vue/nexttick",
    "vue/mixin",
    "vue/slot",
    "vue/observable",
    "vue/key",
    "vue/keepalive",
    "vue/modifier",
    "vue/directive",
    "vue/filter",
    "vue/vnode",
    "vue/diff",
    "vue/axios",
    "vue/axiosCode",
    "vue/ssr",
    "vue/structure",
    "vue/permission",
    "vue/cors",
    "vue/404",
    "vue/error",
    "vue/vue3_vue2"
  ],
  Vue3系列: [
    "vue3/goal",
    "vue3/performance",
    "vue3/proxy",
    "vue3/composition",
    "vue3/treeshaking",
    "vue3/modal_component"
  ],
  React系列: [
    "React/React",
    "React/Real DOM_Virtual DOM",
    "React/life cycle",
    "React/state_props",
    "React/super()_super(props)",
    "React/setState",
    "React/SyntheticEvent",
    "React/Binding events",
    "React/Building components",
    "React/communication",
    "React/key",
    "React/React refs",
    "React/class_function component",
    "React/controlled_Uncontrolled",
    "React/High order components",
    "React/React Hooks",
    "React/import css",
    "React/animation",
    "React/redux",
    "React/Redux Middleware",
    "React/how to use redux",
    "React/React Router",
    "React/React Router model",
    "React/immutable",
    "React/render",
    "React/improve_render",
    "React/diff",
    "React/Fiber",
    "React/JSX to DOM",
    "React/Improve performance",
    "React/capture error",
    "React/server side rendering",
    "React/summary"
  ],
  Webpack系列: [
    "webpack/webpack",
    "webpack/build_process",
    "webpack/Loader",
    "webpack/Plugin",
    "webpack/Loader_Plugin",
    "webpack/HMR",
    "webpack/proxy",
    "webpack/performance",
    "webpack/improve_build",
    "webpack/Rollup_Parcel_snowpack_Vite"
  ],
  TypeScript系列: [
    "typescript/typescript_javascript",
    "typescript/data_type",
    "typescript/enum",
    "typescript/interface",
    "typescript/class",
    "typescript/function",
    "typescript/generic",
    "typescript/high type",
    "typescript/decorator",
    "typescript/namespace_module",
    "typescript/react",
    "typescript/vue"],
  HTTP系列: [
    "http/HTTP_HTTPS",
    "http/HTTPS",
    "http/UDP_TCP",
    "http/OSI",
    "http/TCP_IP",
    "http/DNS",
    "http/CDN",
    "http/1.0_1.1_2.0",
    "http/status",
    "http/GET_POST",
    "http/headers",
    "http/after_url",
    "http/handshakes_waves",
    "http/WebSocket"],
  NodeJS系列: ["NodeJS/nodejs",
    "NodeJS/global",
    "NodeJS/process",
    "NodeJS/fs",
    "NodeJS/Buffer",
    "NodeJS/Stream",
    "NodeJS/EventEmitter",
    "NodeJS/event_loop",
    "NodeJS/require_order",
    "NodeJS/middleware",
    "NodeJS/jwt",
    "NodeJS/file_upload",
    "NodeJS/paging",
    "NodeJS/performance"],
  算法与数据结构系列: [
    "algorithm/Algorithm",
    "algorithm/time_space",
    "algorithm/structure",
    "algorithm/stack_queue",
    "algorithm/Linked List",
    "algorithm/set",
    "algorithm/tree",
    "algorithm/Heap",
    "algorithm/graph",
    "algorithm/sort",
    "algorithm/bubbleSort",
    "algorithm/selectionSort",
    "algorithm/insertionSort",
    "algorithm/mergeSort",
    "algorithm/quickSort",
    "algorithm/BinarySearch",
    "algorithm/design1",
    "algorithm/design2"],
  小程序系列: [
    "applet/applet",
    "applet/lifecycle",
    "applet/navigate",
    "applet/optimization",
    "applet/login",
    "applet/publish",
    "applet/requestPayment",
    "applet/WebView_jscore"],
  设计模式系列: [
    "design/design",
    "design/Singleton Pattern",
    "design/Factory  Pattern",
    "design/Strategy Pattern",
    "design/Proxy Pattern",
    "design/Observer  Pattern"],
  操作系统系列: [
    "linux/linux",
    "linux/thread_process",
    "linux/file",
    "linux/vim",
    "linux/linux users",
    "linux/redirect_pipe",
    "linux/shell"],
  版本控制系列: [
    "git/Version control",
    "git/Git",
    "git/fork_clone_branch",
    "git/command",
    "git/HEAD_tree_index",
    "git/git pull _git fetch",
    "git/git stash",
    "git/git rebase_ git merge",
    "git/conflict",
    "git/git reset_ git revert"],
}
const PREFIX = "interview"
const changeToSideBar = (obj) => {
  return Object.entries(obj).map(([key, value]) => {
    return {
      text: key,
      link: `/${PREFIX}/${value?.[0]}`,
      collapsable: true,
      children: value.map(i => `/${PREFIX}/${i}`)
    }
  })
}

const sidebarList = changeToSideBar(CATALOG)
export default sidebarList
